# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ghost_pb2 as ghost__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ghost_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SNAServiceStub(object):
    """Ghost Agent -> SNA Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/ghost.SNAService/HealthCheck',
                request_serializer=ghost__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=ghost__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetGlobalModel = channel.unary_unary(
                '/ghost.SNAService/GetGlobalModel',
                request_serializer=ghost__pb2.GlobalModelRequest.SerializeToString,
                response_deserializer=ghost__pb2.GlobalModelResponse.FromString,
                _registered_method=True)
        self.SubmitUpdate = channel.unary_unary(
                '/ghost.SNAService/SubmitUpdate',
                request_serializer=ghost__pb2.GhostPackRequest.SerializeToString,
                response_deserializer=ghost__pb2.GhostPackResponse.FromString,
                _registered_method=True)
        self.GetTokenBalance = channel.unary_unary(
                '/ghost.SNAService/GetTokenBalance',
                request_serializer=ghost__pb2.TokenBalanceRequest.SerializeToString,
                response_deserializer=ghost__pb2.TokenBalanceResponse.FromString,
                _registered_method=True)
        self.GetReputationStatus = channel.unary_unary(
                '/ghost.SNAService/GetReputationStatus',
                request_serializer=ghost__pb2.ReputationRequest.SerializeToString,
                response_deserializer=ghost__pb2.ReputationResponse.FromString,
                _registered_method=True)
        self.StreamTrainingEvents = channel.unary_stream(
                '/ghost.SNAService/StreamTrainingEvents',
                request_serializer=ghost__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=ghost__pb2.TrainingEvent.FromString,
                _registered_method=True)


class SNAServiceServicer(object):
    """Ghost Agent -> SNA Service
    """

    def HealthCheck(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGlobalModel(self, request, context):
        """Get current global model
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitUpdate(self, request, context):
        """Submit Ghost Pack (model update)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTokenBalance(self, request, context):
        """Get HealthToken balance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReputationStatus(self, request, context):
        """Get reputation status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTrainingEvents(self, request, context):
        """Stream training events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SNAServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=ghost__pb2.HealthCheckRequest.FromString,
                    response_serializer=ghost__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetGlobalModel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGlobalModel,
                    request_deserializer=ghost__pb2.GlobalModelRequest.FromString,
                    response_serializer=ghost__pb2.GlobalModelResponse.SerializeToString,
            ),
            'SubmitUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitUpdate,
                    request_deserializer=ghost__pb2.GhostPackRequest.FromString,
                    response_serializer=ghost__pb2.GhostPackResponse.SerializeToString,
            ),
            'GetTokenBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenBalance,
                    request_deserializer=ghost__pb2.TokenBalanceRequest.FromString,
                    response_serializer=ghost__pb2.TokenBalanceResponse.SerializeToString,
            ),
            'GetReputationStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReputationStatus,
                    request_deserializer=ghost__pb2.ReputationRequest.FromString,
                    response_serializer=ghost__pb2.ReputationResponse.SerializeToString,
            ),
            'StreamTrainingEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTrainingEvents,
                    request_deserializer=ghost__pb2.StreamEventsRequest.FromString,
                    response_serializer=ghost__pb2.TrainingEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ghost.SNAService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ghost.SNAService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SNAService(object):
    """Ghost Agent -> SNA Service
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.SNAService/HealthCheck',
            ghost__pb2.HealthCheckRequest.SerializeToString,
            ghost__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGlobalModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.SNAService/GetGlobalModel',
            ghost__pb2.GlobalModelRequest.SerializeToString,
            ghost__pb2.GlobalModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.SNAService/SubmitUpdate',
            ghost__pb2.GhostPackRequest.SerializeToString,
            ghost__pb2.GhostPackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTokenBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.SNAService/GetTokenBalance',
            ghost__pb2.TokenBalanceRequest.SerializeToString,
            ghost__pb2.TokenBalanceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReputationStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ghost.SNAService/GetReputationStatus',
            ghost__pb2.ReputationRequest.SerializeToString,
            ghost__pb2.ReputationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTrainingEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ghost.SNAService/StreamTrainingEvents',
            ghost__pb2.StreamEventsRequest.SerializeToString,
            ghost__pb2.TrainingEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
